server:
  port: 8080
---
spring:
  pid:
    file: foresys-vacation.pid
---
server:
  tomcat:
    additional-tld-skip-patterns: "*.jar"
---
# DB setting
spring:
  datasource:
    driver-class-name: "oracle.jdbc.OracleDriver"
    url: ""
    username: ""
    password: ""
---
# XML location
mybatis:
    mapper-locations: classpath:mappers/**/*.xml