server:
  port: 8080
---
spring:
  pid:
    file: foresys-vacation.pid
---
server:
  tomcat:
    additional-tld-skip-patterns: "*.jar"
---
# DB setting
spring:
  datasource:
    driver-class-name: "oracle.jdbc.OracleDriver"
    url: "jdbc:oracle:thin:@172.16.32.211:1521:orcl"
    username: "SUPPORT"
    password: "SUPPORT"
---
# XML location
mybatis:
    mapper-locations: classpath:mappers/**/*.xml